### ISSUE TITLE
sm.Prs[2].Next - 1 might overflow 

### ISSUE THREAD

**Issue by miamia0** [talent-plan/tinykv#209]
https://github.com/pingcap-incubator/tinykv/blob/3513f5d1b42e9a50eafe54b002370b8851d517a8/raft/raft_test.go#L1033-L1034

`sm.Prs[2].Next`  is a uint64 variable，after `sm.Prs[2].Next=0`， ` sm.Prs[2].Next - 1 `might overflow .

**Comment by Connor1996** [comment]
PTAL @NingLin-P

**Comment by NingLin-P** [comment]
@miamia0  Thanks for reporting this bug! Would you like to send a pr to fix it? We can just setting`sm.Prs[2].Next = 1` since log entries before the snapshot index `11` are compacted, also instead of `MsgAppendResponse`, sending `MsgPropose` message to trigger snapshot will be better as we don't enforce people how to use the `Index` field.
