### ISSUE TITLE
2b tests consume too much memory

### ISSUE THREAD

**Issue by yujqiao** [talent-plan/tinykv#238]
The memory usage of `make project2b` grows from 2GiB to 12GiB on my machine. It seems that a test like `BasicTets` won't release memory even after it passes. So the memory usage just grows monotonically. Also, splitting up the test by manually running `go test` won't take that much memory. Is there a potential memory leak?

OS: Arch Linux
Kernel: 5.10.10-arch1-1

**Comment by Connor1996** [comment]
Nice finding. I didn't pay much attention to the memory usage and it's possible a memory leak somewhere.
You could investigate deeper by go pprof, it would be a really great contribution.

**Comment by YangKian** [comment]
I think the main cause of the memory leak may be badger. There is an Iterator interface in `y/iterator.go` (https://github.com/Connor1996/badger/blob/9bbcbd8ba570f09f3f2f395b11a6385a14750237/y/iterator.go#L71), but it doesn't support a `Close` method.

```
type Iterator interface {
	Next()
	Rewind()
	Seek(key []byte)
	Key() []byte
	Value() ValueStruct
	FillValue(vs *ValueStruct)
	Valid() bool
}
```

So all the places in badger where the Iterator interface is used do not perform the iterator close operation.
Since I'm quite unfamiliar with badger and LSM Tree, I have some try but finally failed to fix it. Just given my guess and may it helps _(:з」∠)_

**Comment by wangnengjie** [comment]
Yes. The problem is that memory won't be released when one test finished. I run `TestSnapshotRecoverManyClients2C`  three times and get flame graph(graph for inuse_space) like this:
![37BEB397-83F8-43A6-B2B6-19296D298FB3](https://user-images.githubusercontent.com/43722125/106386242-08cef500-640f-11eb-8823-1fc2ce50e617.png)
The memory use is nearly three times than run the test once. And the memory used by badger is huge. Badger may have a memory leak bug.
On the other hand, the default badger option `MaxCacheSize`is 1GB. With 5 raftstore in test, it will cause atmost 5GB memory use. But it's not a big deal if memory leak bug can be fixed.

So in what case will the memory be used even after the test func returned? Hanging Goroutines which refer to something large?
> I think the main cause of the memory leak may be badger. There is an Iterator interface in y/iterator.go (https://github.com/Connor1996/badger/blob/9bbcbd8ba570f09f3f2f395b11a6385a14750237/y/iterator.go#L71), but it doesn't support a Close method.

It's a nice guess. 
Emm...I'm unfamiliar with badger and LSM Tree too...

**Comment by Connor1996** [comment]
> Yes. The problem is that memory won't be released when one test finished. I run `TestSnapshotRecoverManyClients2C` three times and get flame graph(graph for inuse_space) like this:
> ![37BEB397-83F8-43A6-B2B6-19296D298FB3](https://user-images.githubusercontent.com/43722125/106386242-08cef500-640f-11eb-8823-1fc2ce50e617.png)
> The memory use is nearly three times than run the test once. And the memory used by badger is huge. Badger may have a memory leak bug.
> On the other hand, the default badger option `MaxCacheSize`is 1GB. With 5 raftstore in test, it will cause atmost 5GB memory use. But it's not a big deal if memory leak bug can be fixed.
> 
> So in what case will the memory be used even after the test func returned? Hanging Goroutines which refer to something large?
> 
> > I think the main cause of the memory leak may be badger. There is an Iterator interface in y/iterator.go (https://github.com/Connor1996/badger/blob/9bbcbd8ba570f09f3f2f395b11a6385a14750237/y/iterator.go#L71), but it doesn't support a Close method.
> 
> It's a nice guess.
> Emm...I'm unfamiliar with badger and LSM Tree too...

Some thoughts:
1. Check if `Close()` is correctly called on badger
2. Run the test once and pause before the test is returned. See if there is any goroutine of badger that doesn't exit.
3. Maybe due to the iterator, you can take a deep look at badger if you're interested.

**Comment by wangnengjie** [comment]
Oh, I'm not familier with pprof and forgot this way.
I now get two hanging goroutine `badger/epoch.(*ResourceManager).collectLoop` and `badger.(*blobGCHandler).run`.
And the problem seems to have been solved in the upstream [pingcap/badger](https://github.com/pingcap/badger). Both has a close channel now, which implement in here https://github.com/pingcap/badger/blob/2e78ee155d19c598f2533c9480b8e93591bc3d10/y/y.go#L142

**Comment by Connor1996** [comment]
The used badger has close channel too. I see no difference with the upstream. https://github.com/Connor1996/badger/blob/9bbcbd8ba570f09f3f2f395b11a6385a14750237/y/y.go#L173

You can dump the stack of the two hanging goroutines to see what are they waiting for.

**Comment by wangnengjie** [comment]
Sorry, I say here https://github.com/pingcap/badger/blob/2e78ee155d19c598f2533c9480b8e93591bc3d10/epoch/manager.go#L97-L108
and here
https://github.com/pingcap/badger/blob/2e78ee155d19c598f2533c9480b8e93591bc3d10/blob.go#L465-L479
I will try if this can fix later.

**Comment by Connor1996** [comment]
Great!

**Comment by wangnengjie** [comment]
I run test like this on macos.
```go
func TestSnapshotRecoverManyClients2C(t *testing.T) {
	GenericTest(t, "2C", 20, false, true, false, 100, false, false)
	runtime.GC()
	var stat runtime.MemStats
	runtime.ReadMemStats(&stat)
	fmt.Printf("alloc:%d TotalAlloc:%d Sys:%d HeapAlloc:%d HeapSys:%d HeapIdle:%d HeapInuse:%d HeapReleased:%d\n",
		stat.Alloc, stat.TotalAlloc, stat.Sys, stat.HeapAlloc, stat.HeapSys, stat.HeapIdle, stat.HeapInuse, stat.HeapReleased)
}
```
```
go test -v --count=3 --parallel=1 -p=1 ./kv/test_raftstore -run TestSnapshotRecoverManyClients2C
```
Before the fix:
```
alloc:5040538168 TotalAlloc:28924517008 Sys:13124814120 HeapAlloc:5040538168 HeapSys:12480872448 HeapIdle:7431766016 HeapInuse:5049106432 HeapReleased:14123008
alloc:10042791448 TotalAlloc:52761397968 Sys:21976665296 HeapAlloc:10042791448 HeapSys:21003436032 HeapIdle:10948214784 HeapInuse:10055221248 HeapReleased:35209216
alloc:15029063808 TotalAlloc:74342269368 Sys:29896260576 HeapAlloc:15029063808 HeapSys:28586573824 HeapIdle:13540573184 HeapInuse:15046000640 HeapReleased:8159232
```
After the fix:
```
alloc:4032683168 TotalAlloc:25218286200 Sys:13101221160 HeapAlloc:4032683168 HeapSys:12480839680 HeapIdle:8441626624 HeapInuse:4039213056 HeapReleased:15171584
alloc:4035123312 TotalAlloc:52236965344 Sys:13126845736 HeapAlloc:4035123312 HeapSys:12480839680 HeapIdle:8439037952 HeapInuse:4041801728 HeapReleased:6815744
alloc:4035653872 TotalAlloc:76663950984 Sys:13750321520 HeapAlloc:4035653872 HeapSys:13084852224 HeapIdle:9041944576 HeapInuse:4042907648 HeapReleased:349200384
```
But it still use too many memory...There must be something I ignored. Maybe I should have a read about memory management of golang.
By the way, the memory use grow from 6G to 12 G(just a fuzzy number) in a sudden. This is strange. I currently didn't locate it.

**Comment by Connor1996** [comment]
The `alloc` is greatly reduced, seems it's indeed due to the leaky goroutines. Would you mind sending a PR for Connor/badger and update it in tinykv?

As for the memory is still large(from the HeapSys, it's about 12G and HeapIdle accounts for 8G), maybe it's due to go runtime doesn't return the idle heap memory immediately to the system. I'm not familiar with go runtime, don't know if it is as expected  /cc @bobotu

**Comment by Connor1996** [comment]
I guess, the sudden growth from 6G to 12G is because of a peak memory usage somewhere, e.g. the messages are stashed in channel to simulate network latency. Maybe you can get a perf when the test is running or run a goroutine to check the memory stats periodically and dump the perf when HeapInuse rises greatly.

**Comment by wangnengjie** [comment]
OKay. I guess [ristretto](https://github.com/dgraph-io/ristretto) used by badger may have leak as well. Just a guess. The `alloc` 4GB is used by it and in the code, I read MemStats just after the test. Ristretto is about go cache. I'm not famillier. There might be some tricky about os. Out of my ability...
The memory sudden growth is still a problem. When running the test the first time, it only consume about 6GB steady. And you can see when read memstat the first time after the test, it use about 12GB and with 8GB idle...
> I guess, the sudden growth from 6G to 12G is because of a peak memory usage somewhere, e.g. the messages are stashed in channel to simulate network latency. Maybe you can get a perf when the test is running or run a goroutine to check the memory stats periodically and dump the perf when HeapInuse rises greatly.

I will have a try.

**Comment by bobotu** [comment]
> OKay. I guess [ristretto](https://github.com/dgraph-io/ristretto) used by badger may have leak as well. Just a guess. The `alloc` 4GB is used by it and in the code, I read MemStats just after the test. Ristretto is about go cache. I'm not famillier. There might be some tricky about os. Out of my ability...
> 
> The memory sudden growth is still a problem. When running the test the first time, it only consume about 6GB steady. And you can see when read memstat the first time after the test, it use about 12GB and with 8GB idle...
> 
> > I guess, the sudden growth from 6G to 12G is because of a peak memory usage somewhere, e.g. the messages are stashed in channel to simulate network latency. Maybe you can get a perf when the test is running or run a goroutine to check the memory stats periodically and dump the perf when HeapInuse rises greatly.
> 
> 
> 
> I will have a try.

This cache will preallocate 4GB chunk and hold it forever. This is an internal sketch to help cache works correctly.

According to Go's GC strategy, if you have 4GB live objects the GC will be triggered when memory usage reach 8GB. So this is the reason for so called suddenly increase.

You do not need to change any code if you just what to trigger GC more eagerly, GOGC is here for you.

If you what to decrease overall memory usage, change the configuration of the cache is also a good option.
