### ISSUE TITLE
confuse of clearExtraData in ApplySnapshot

### ISSUE THREAD

**Issue by Yxa2111** [talent-plan/tinykv#274]
1. I found a helper function `engine_util.ExceedEndKey()`:https://github.com/tidb-incubator/tinykv/blob/b4b7dca34ff1ebefa0a5844f08424224c888b620/kv/util/engine_util/util.go#L105-L110

When endKey equals to "", it stands for +infinity, So we need check it first, then use `byte.Compare` to compare them.

But in https://github.com/tidb-incubator/tinykv/blob/b4b7dca34ff1ebefa0a5844f08424224c888b620/kv/raftstore/peer_storage.go#L264

it compare them directly. Is it a bug?

2. When I running test, i met a situation:

If there are two store: 

| nodeId | store | region | state | range |
| ---- | ---- | ---- | ---- | ---- |
| 1 | 1 | 1 | Leader | ["1", "2"] |
| 2 | 2 | 1 | follower | ["1", "4"] |
| 7 | 2 | 6 | leader | ["2", "4"] |

region 1 split a new region 7 and split key is "2". Then node 1 send snapshot to 2, it update new region info and call `clearExtraData` to clean data range ["2", "4"] in store 2. But node 7 also in store 2 and it's a leader. Then it execute client command like "Get", it will not found it's data in the store. So why we need call `clearExtraData` in `ApplySnapshot`?

**Comment by JGEthanChen** [comment]
Node 7 should be in store 1,  because it split from node 1, I think.
Did you mean region 1 current leader 1 split firstly, and region 1 follower 2 had not split yet,  then 1 sent a snapshot to  2， which made 2 clearExtraData clean the data range ?
In this case, when 2 process the split command, and split a new node in region 6 at store 2, the new node will receive its leader's snapshot,  and get the data in range ["2", "4"] again. Perhaps this leader is node 7 in region1 at store 1.

**Comment by Yxa2111** [comment]
@Whorra Thank you, maybe I was mistaken.

**Comment by Yxa2111** [comment]
> Node 7 should be in store 1, because it split from node 1, I think.
> Did you mean region 1 current leader 1 split firstly, and region 1 follower 2 had not split yet, then 1 sent a snapshot to 2， which made 2 clearExtraData clean the data range ?
> In this case, when 2 process the split command, and split a new node in region 6 at store 2, the new node will receive its leader's snapshot, and get the data in range ["2", "4"] again. Perhaps this leader is node 7 in region1 at store 1.

@Whorra Thank you, maybe I was mistaken.

**Comment by JGEthanChen** [comment]
You are welcome.😊 And I met the same problem in clearExtraData as you describe. 
I think it would go wrong if the old end key is "", and new end key is not "". For example, if the old end key is "", and new end key is "3". After comparing, clear would not happen because "3" > "".  
Replace like that maybe help.
``` go
if bytes.Compare(newEndKey, oldEndKey) < 0 || len(oldEndKey) == 0 {
```

**Comment by gitccl** [comment]
> Node 7 should be in store 1, because it split from node 1, I think. Did you mean region 1 current leader 1 split firstly, and region 1 follower 2 had not split yet, then 1 sent a snapshot to 2， which made 2 clearExtraData clean the data range ? In this case, when 2 process the split command, and split a new node in region 6 at store 2, the new node will receive its leader's snapshot, and get the data in range ["2", "4"] again. Perhaps this leader is node 7 in region1 at store 1.
I have some question about clearExtraData:
1. We cannot guarantee that the leader is node 7 in region1 at store 1, other nodes can also be elected as leader.
2. Assume node 7 in region1 at store 1 is leader after split, it may keeps synchronous with the follower on store 2, so it needn't send snapshot. But the Key-Value of the follower on store 2 was cleared by node 2 on store 2 due to node 2 receives a snapshot from node 1(Leader).
