### ISSUE TITLE
Question on project2ab test case TestLeaderSyncFollowerLog2AB

### ISSUE THREAD

**Issue by YECHUNAN** [talent-plan/tinykv#457]
I need some help to understand what I am missing in order to pass this test case. Based on my understanding, the followers only rely on heartbeat/appendEntry messages to sync their commit index with the leader. However, in TestLeaderSyncFollowerLog2AB, it requires the follower to sync its commit index immediately after processing an AppendEntry message.

Here is a quote of the test case:
```go
n.send(pb.Message{From: 1, To: 1, MsgType: pb.MessageType_MsgPropose, Entries: []*pb.Entry{{}}})

if g := diffu(ltoa(lead.RaftLog), ltoa(follower.RaftLog)); g != "" {
	t.Errorf("#%d: log diff:\n%s", i, g)
}
```

Propose message should trigger broadcasting AppendEntry to followers without triggering any additional heartbeat or appendEntry messages, assuming there is no conflict or missing entry. Is this understanding correct? Without calling Step after the Propose, I cannot see how the follower can update its commit index to be identical to the leader's because the leader has no way to tell the followers that a quorum has been found without sending a heartbeat or appendEntry message.

If I make a request to the leader in the visualization tool on https://raft.github.io/, it can be seen that the commit index of the followers are off by one after the leader receives a majority of append entry responses but before the next heartbeat message reaches the followers, which I think contradicts what this test case is checking for.

**Comment by YECHUNAN** [comment]
I see, the readme said this

```
The tests assume that once the leader advances its commit index, it will broadcast the commit index by MessageType_MsgAppend messages.
```

It's odd that this is something that the test cases require the implementation to do instead of ensuring within the test cases themselves since eventually a heartbeat will occur to sync the commit index which means it's not necessary to immediately broadcast appendEntries after advancing the commit index in the leader.

**Comment by onford** [comment]
@YECHUNAN Hello! I'm confused by this test case too. May I ask you where did you see that readme? In the annotation of test case `TestLeaderCommitEntry2AB` in `raft_paper_test.go`, it is said "the leader keeps track of the highest index it knows to be committed, and it includes that index in **future** AppendEntries RPCs so that the other servers eventually find out", which is contradict to our conclusion that the leader immediately broadcast the commit index upon the its advance. Have you passed the `TestLeaderCommitEntry2AB` test?
